SILVER-270 - Add support for GitHub Apps
simplybusiness/deploy-status-action pull request #220
Opened 2024-09-19 08:59 UTC by moltenice

The action now supports a client ID and client secret as authentication. This is usually what's needed for authenticating as a GitHub App.

I wanted to keep support for PAT tokens as I reckon in some places - both within Simply Business and in the open source community - people might still find it easier to use.

2024-09-19 09:11 UTC, addersuk requested changes
This is doing auth to impresionate someone, we need an app installation via a JWT https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app

2024-09-19 09:11 UTC, addersuk commented on lib/config/github_api_config.rb
> +              else
In v2 we do not want to support PATs

2024-09-19 09:34 UTC, moltenice commented
> This is doing auth to use oauth client credentials, we need an app installation via a JWT https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app

I am pretty sure this internally uses JWK to do so: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app#using-the-octokitjs-sdk-to-authenticate-as-a-github-app

2024-09-24 09:24 UTC, moltenice commented on README.md
>             uses: simplybusiness/deploy-status-action@v0.4.1
@addersuk I was thinking of changing this after this PR but sure.

2024-09-24 09:25 UTC, addersuk commented on README.md
>             uses: simplybusiness/deploy-status-action@v0.4.1
So either don't add the new parameters, or bump to v2

2024-09-24 09:25 UTC, moltenice commented on README.md
>             uses: simplybusiness/deploy-status-action@v0.4.1
Bumped to v2

2024-09-24 09:30 UTC, addersuk approved these changes

2024-09-24 09:33 UTC, merged